#!/bin/bash
# 
# eg: issuecode version online_server1,online_server2
#
#

##########diy opt##########
ISSUEDIR='issuepack'
###########################


LASTVER=$1
SERVER=$2

# while getopts :v:s: arg;
# do
#     case $arg in
#          v)
#             LASTVER="$OPTARG" ;;
#          s)
#             SERVER="$OPTARG" ;;
#          ?)
#             echo "unkonw argument"
#             exit 1 ;;
#     esac
# done

# echo $arg

# echo $LASTVER
# echo $SERVER
# exit




#############
PROJECT_HOME=`pwd`
cd ~
USER_HOME=`pwd`
cd $PROJECT_HOME
#############



function UPDATE_PACKNAME(){
    TIME=$(date +%Y%m%d%H%M%S)
    PROJECTNAME=`basename $PROJECT_HOME`
    PACKNAME="$PROJECTNAME-$VERSION-$TIME.zip"
    
    if [ -n "~/$ISSUEDIR" ]; then
      mkdir -p ~/$ISSUEDIR
    fi
    
    PACKPATH="$USER_HOME/$ISSUEDIR/$PACKNAME"
}

function GET_VERSION(){
    if [ -n "$LASTVER" ]; then
      VERSION=$LASTVER
      LASTVER="HEAD $LASTVER"
    else
      VERSION='HEAD'
      LASTVER='HEAD^ HEAD'
    fi
}

function OUTPUT_CODE(){
    echo "Packname: $PACKNAME"
    echo "Path: $PACKPATH"
    git pull
    git archive -o $PACKPATH HEAD $(git diff --name-only $LASTVER)
}




GET_VERSION
UPDATE_PACKNAME
OUTPUT_CODE
