#!/bin/bash
#

##########diy opt##########
ISSUEDIR='issuepack'
###########################

PROJECT_HOME=`pwd`
cd ~
USER_HOME=`pwd`
cd $PROJECT_HOME
#############


ISLOGIN=false


while getopts "v:s:l" arg;
do
  case $arg in
    "v")
      LASTVER="$OPTARG" ;;
    "s")
      SERVER="$OPTARG" ;;
    "l")
      ISLOGIN=true ;;
    "?")
      echo "Usege: issuecode [-v] [-s] [-l]"
      echo "eg: issuecode -v 9867e -s server1 -l"
      exit 1 ;;
  esac
done



function UPDATE_PACKNAME(){
  TIME=$(date +%Y%m%d%H%M%S)
  PROJECTNAME=`basename $PROJECT_HOME`
  PACKNAME="$PROJECTNAME-$VERSION-$TIME.zip"
  
  if [ -n "$USER_HOME/$ISSUEDIR" ]; then
    mkdir -p $USER_HOME/$ISSUEDIR
  fi
  
  PACKPATH="$USER_HOME/$ISSUEDIR/$PACKNAME"
}

function GET_VERSION(){
  if [ -n "$LASTVER" ]; then
    VERSION=$LASTVER
    LASTVER="HEAD $LASTVER"
  else
    VERSION='HEAD'
    LASTVER='HEAD^ HEAD'
  fi
}

function OUTPUT_CODE(){
  echo "Packname: $PACKNAME"
  echo "Path: $PACKPATH"
  git pull
  git archive -o $PACKPATH HEAD $(git diff --name-only $LASTVER)
}

function SSH_SEND_PACK(){
  if [ -n "$SERVER" ]; then
    echo "Ssh Upload: scp $PACKPATH $SERVER:~/"
    scp $PACKPATH $SERVER:~/
  fi

  if [ $ISLOGIN = true ]; then
    echo "Login $SERVER ..."
    ssh $SERVER
  fi
}



GET_VERSION
UPDATE_PACKNAME
OUTPUT_CODE
SSH_SEND_PACK
